services:
  web:
    build: ./
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./backend:/usr/src/app/backend
      - ./workspaces:/usr/src/app/workspaces
      - ./examples:/usr/src/app/examples
      # Маскируем локальную папку, чтобы использовать модули из контейнера
      - /usr/src/app/backend/node_modules
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HTTPS_PORT=8443
      - USE_HTTPS=true
      - MAX_WORKSPACE_SIZE=100MB
      - "PYTHONBUFFERED=1"
    restart: unless-stopped
    networks:
      - esp32-net

  compiler:
    build:
      context: .
      dockerfile: docker/Dockerfile.compiler
    volumes:
      - ./workspaces:/workspaces
      - compiler-cache:/root/.platformio
      - compiler-packages:/root/.platformio/packages
    environment:
      - ESPTOOL_VERSION=5.1.0
      - PIO_CACHE_DIR=/root/.platformio
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/bus/usb:/dev/bus/usb:rw
    privileged: true
    networks:
      - esp32-net
    restart: unless-stopped

  esptool:
    build:
      context: .
      dockerfile: docker/Dockerfile.esptool
    volumes:
      - ./workspaces:/workspaces
      - /dev/bus/usb:/dev/bus/usb:rw
    privileged: true
    networks:
      - esp32-net
    restart: unless-stopped

volumes:
  compiler-cache:
  compiler-packages:

networks:
  esp32-net:
    driver: bridge
